### ISSUE TITLE
Install command didn’t return non-zero exit code on error

### ISSUE THREAD

**Issue by Mystik738** [alexellis/k3sup#149]
When running k3sup, one would expect its own exit codes to report errors if it encounters errors

## Expected Behaviour
non-zero exit codes on error

## Current Behaviour
zero exit codes on error

## Steps to Reproduce (for bugs)
k3sup install --ip 0.0.0.0 && echo "$?"
Running: k3sup install
Public IP: 0.0.0.0
ssh -i /home/robert/.ssh/id_rsa -p 22 root@0.0.0.0
Error: unable to connect to 0.0.0.0:22 over ssh: dial tcp 0.0.0.0:22: connect: connection refused
0

## Context
I'd like to run k3sup as part of an ansible playbook and have it report when it fails. Currently with the zero exit codes, it doesn't

## Your Environment
Ubuntu 18.04

**Comment by alexellis** [comment]
Hi k3sup does many things now so the title of this issue is not specific enough, please update it with your specific usecase.

I think we can fix this, but I'm surprised that it didn't return a non zero. I think this needs fixing. Your SSH connection also needs fixing by the sounds of it 🤓

Would you be willing to send a PR yourself, or would you like me to find someone else?

Alex

**Comment by alexellis** [comment]
/set title: Install command didn’t return non-zero exit code on error

**Comment by alexellis** [comment]
Hi we've fixed this :) Do you have a link to your playbook?
