### ISSUE TITLE
Help wanted: Test on Windows 10

### ISSUE THREAD

**Issue by alexellis** [alexellis/k3sup#15]
## Expected Behaviour

I'd like to know if `k3sup` works on Windows 10, and if not, what is needed to make that possible.

## Current Behaviour

Users can download the code and rebuild on Windows using Go to find out.

## Context

It would be good to offer a binary for the main OSes

**Comment by michaelkacher** [comment]
The preliminary test of go getting, building, and running on windows 10 works but did not have time to extensively test before the coffee ran out and time to get ready for work.  If there are any specific tests, etc. to run I can do it tonight.

**Comment by alexellis** [comment]
Thank you @michaelkacher  :muscle: 

It'd be great to get a few people to grab the code, build it and then run the install command against a cluster, followed by checking that the kubeconfig worked. Then to join another host and check that it was successful.

In other words, an e2e test using the example in the README.md file.

**Comment by alexellis** [comment]
1) Download Go 1.11.13 for Windows https://golang.org/dl/
2) Install Go
3) Set your GOPATH environment variable to a set path
4) Run `go get github.com/alexellis/k3sup`
5) Visit the folder in `GOPATH\src\github.com\alexellis\k3sup`
6) Try `k3sup.exe` with the instructions in the README.md file
7) Report back

**Comment by alexellis** [comment]
Given feedback on [Twitter from Ganesh](https://twitter.com/vattybear/status/1163433554627432448?s=20) and from Michael, I've gone ahead and released a cross-compiled .exe for use on Windows.

https://github.com/alexellis/k3sup/releases/tag/0.2.2

It would be great to get some testing on it before closing this issue.

Alex

**Comment by vattybear** [comment]
Test of cross-compiled .exe on Windows 10 Pro build 1903.
Test run against Raspberry pi on local network with a pre-installed k3s.

Steps
1) Download release as of today : https://github.com/alexellis/k3sup/releases/download/0.2.2/k3sup.exe
2) k3sup install --skip-install --ip 192.168.0.93 --user pi
Result : 
Saving file to: C:\Users\Ganesh\k3sup\upstream\kubeconfig

3) Set Kubeconfig environment variable  to result from previous command 
C:\Users\Ganesh\k3sup\upstream>set KUBECONFIG=C:\Users\Ganesh\k3sup\upstream\kubeconfig

4) Run kubectl against k3s on raspberry pi 
C:\Users\Ganesh\k3sup\upstream>kubectl get nodes
NAME    STATUS   ROLES    AGE   VERSION
pi3s1   Ready    master   22d   v1.14.4-k3s.1

Result : Success!

**Comment by vattybear** [comment]
General requirements / some recommendations for Windows users.
In this example 192.168.0.93 references to my target raspberry pi device on which I am installing and running k3s.   
Please replace my name with your own desktop username...

1) SSH
k3sup uses ssh to configure nodes and windows does not have native ssh installed.
One easy way on Windows 10 is to turn on "additional feature for openssh".
Please see : 
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

2)key setup
There is no ssh-copy-id in openssh install on windows (from step 1)
After generating a key on windows with ssh-keygen, I used a quick/dirty method of adding my key to the raspberry pi  by manually editing  ~/.ssh/authorized_keys and copying the string from c:\Users\Ganesh\.ssh\id_rsa.pub . 

3) Installing Go / Virtualbox / kubectl on windows 
I am a fan of chocolatey to install and maintain local software. https://chocolatey.org/ 
With this to install Go was just a "choco install golang" (if compiling from source) and "choco install kubernetes-cli" and I had both golang and kubectl ready to go

4) GOPATH
When attempting to compile main.go from k3sup - I had to understand where golang was looking for the imported packages 
	"github.com/alexellis/k3sup/pkg/cmd"
	"github.com/spf13/cobra"

I got errors like : 
cobra\command_win.go:10:2: cannot find package "github.com/inconshreveable/mousetrap" in any of:
        c:\go\src\github.com\inconshreveable\mousetrap (from $GOROOT)
        C:\Users\Ganesh\go\src\github.com\inconshreveable\mousetrap (from $GOPATH)
pkg\cmd\install.go:11:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
        c:\go\src\github.com\mitchellh\go-homedir (from $GOROOT)
        C:\Users\Ganesh\go\src\github.com\mitchellh\go-homedir (from $GOPATH)


So I created a folder structure under c:\users\Ganesh and then did a git clone under that.
i.e.,

mkdir c:\Users\Ganesh\go\src\github.com\allexellis\k3sup
c:\Users\Ganesh\go\src\github.com\allexellis\k3sup
git clone https://github.com/alexellis/k3sup
mkdir c:\Users\Ganesh\go\src\github.com\spf13
git clone https://github.com/spf13/cobra

There is clearly a better way to do this but this worked for me...

5) Bash vs Cmd.exe

To reference environment variables - you cannot use $ like in bash - you need to use %envvar% and you use "set" instead of "export" 
Example : 
set IP=192.168.0.93
set USER=pi
then instead of
k3sup install --skip-install --ip=192.168.0.93 --user=pi
you can use 
k3sup install --skip-install --ip=%IP% --user=%USER%

6) Avoiding all this headache
Use WSL on Windows 10 and use the linux version of k3sup and all other tools...
WSL : https://docs.microsoft.com/en-us/windows/wsl/install-win10

For example on my Ubuntu based WSL 
wget https://github.com/alexellis/k3sup/releases/download/0.2.2/k3sup
chmod +x k3sup
ssh-keygen
ssh-copy-id pi@192.168.0.93 
k3sup

and done - its ready to go!

Hope this is of some help...

**Comment by vattybear** [comment]
Mostly a clone of instructions from readme page but updated for windows specific commands. 

### Environment 
OS: Windows 10
Pre-requisite : 
1) kubectl for windows  (download from [kubernetes.io](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-windows))

2) openssh for windows (see [Microsoft documentation](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse))

3) k3sup (download k3sup.exe from [Release Page](https://github.com/alexellis/k3sup/releases))

### Infrastructure setup: 
Provision (1 or 2) new virtual machine running a compatible operating system such as Ubuntu, Debian, Raspbian, or something else.  
With 1 VM you can just run k3s. 
With 2 you can join the second VM to the first as a worker node.

Assuming you have 2 VM's with `ubuntu` as the user and IP's as `192.168.83.128`, `192.168.83.129` 

Note : ssh-copy-id is not available on openssh for windows. You generate your private/public key and then copy the public key over manually to the linux device.

To generate a new key on windows 
`ssh-keygen`

Now lets copy it over from windows to the remote device (will ask for password this time)

scp c:\user\<your_name>\.ssh\id_rsa.pub  ubuntu@192.168.83.129:/home/ubuntu/key.pub

On the remote linux device - logged in as ubuntu
```
ubuntu@vm1:~$ cat key.pub >>~/.ssh/authorized_keys
ubuntu@vm1:~$ rm key.pub
```
Repeat on second VM (if required)
```
ubuntu@vm2:~$ cat key.pub >>~/.ssh/authorized_keys
ubuntu@vm2:~$ rm key.pub
```

Test from windows by 
`ssh ubuntu@192.168.83.128 `

Aim is that you can login without requiring a password.

Finally you need to ensure you can use sudo on the linux device without requiring a password.
This requires running the following command on the linux device(s)
`sudo visudo`

and adding the following text to the end (which enables the ubuntu user to use sudo without password) 
`ubuntu ALL=(ALL) NOPASSWD: ALL`


### Run `k3sup` :

```
set VM1=192.168.83.128
set VM2=192.168.83.129
set USER=ubuntu 
k3sup install --ip=%VM1% --user=%USER%
```
All this going well - you should now get a lot of text followed by 

`Saving file to: C:\Users\<your_name>\k3sup\upstream\kubeconfig`

Set your environment variable using path from previous command

`set KUBECONFIG=C:\Users\<your_name>\k3sup\upstream\kubeconfig`

Now test with kubectl and you should get remote access to k3s on that remote VM

```
kubectl get nodes -o wide
NAME   STATUS   ROLES    AGE   VERSION         INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
vm1    Ready    master   61s   v1.14.5-k3s.1   192.168.83.128   <none>        Ubuntu 18.04.3 LTS   4.15.0-58-generic   containerd://1.2.7-k3s1
```

**Comment by vattybear** [comment]
### Join some agents to your Kubernetes server
Now to get second VM setup - the infrastructure setup is the same 

```
set VM1=192.168.83.128
set VM2=192.168.83.129
set USER=ubuntu 

k3sup join --ip=%VM2% --server-ip=%VM1% --user=%USER%
```
All this going well - you should now get a lot of text ending with something like
```
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  systemd: Starting k3s-agent
```

Set your environment variable using path from previous command if you are not continuing in same command shell 

`set KUBECONFIG=C:\Users\<your_name>\k3sup\upstream\kubeconfig`

Now test with kubectl and you should get remote access to k3s on that remote VM

```
kubectl get nodes -o wide
NAME   STATUS   ROLES    AGE    VERSION         INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
vm1    Ready    master   9m2s   v1.14.5-k3s.1   192.168.83.128   <none>        Ubuntu 18.04.3 LTS   4.15.0-58-generic   containerd://1.2.7-k3s1
vm2    Ready    worker   83s    v1.14.5-k3s.1   192.168.83.129   <none>        Ubuntu 19.04         5.0.0-25-generic    containerd://1.2.7-k3s1
```

You now have a very similar setup to the Raspberry Pi example on main readme

![image](https://user-images.githubusercontent.com/22106690/63296733-b0ae3c80-c2c7-11e9-9d07-c30649817bd8.png)

**Comment by alexellis** [comment]
RE: `set KUBECONFIG=C:\Users\<your_name>\k3sup\upstream\kubeconfig`

Can this be: %HOMEDIR%\k3sup\` ?

**Comment by vattybear** [comment]
I don't see a pre-built environment variable as %HOMEDIR% on my desktop.
There is a %HOMEDRIVE%=C: and %HOMEPATH%=\Users\<your_name>  which combined make up the full path

So it could be 

set KUBECONFIG=%HOMEDRIVE%%HOMEPATH%\k3sup\kubeconfig

it might be easier to just copy /paste from the output of the k3sup command (it gives full path)
Or maybe an enhancement is to automatically set KUBECONFIG in k3sup if one is not already set?

**Comment by vattybear** [comment]
Is there anything else required on this issue?

**Comment by alexellis** [comment]
Thank you all, I think it would be great to get a little tutorial together on dev.to? Would anyone be willing to write it up over the next week? I'm happy to review and see if it makes sense in the k3sup repo after that.

Alex

**Comment by vattybear** [comment]
I don't have a blog but given I have been meaning to start one for ages, this might be a good excuse to start one on dev.to - I can write up everything here - will ping you once I have something - maybe a few days before I get time to prioritize this...

**Comment by TechGuyTN** [comment]
Were you ever able to get a tutorial together @vattybear ? If not I would be willing to give it a go @alexellis

**Comment by vattybear** [comment]
Hello.. I wrote almost everything for a tutorial into the issue and then lost track... happy for anyone else to pickup on any tutorial since a lot has happened with k3sup and the ecosystem since this issue was originally raised..  thanks! On 24 May 2020 08:20, Aaron Holt <notifications@github.com> wrote:
Were you ever able to get a tutorial together @vattybear ? If not I would be willing to give it a go @alexellis

**Comment by TechGuyTN** [comment]
I've got some time with tomorrow being a holiday here in the USA, I will give it a go and report back sometime in the next few days @vattybear

**Comment by TechGuyTN** [comment]
OK so over the last 4 hours I have put together a rough draft, this is the install that worked for me. If you have any suggestions please feel free to make a PR. @vattybear 

If you find this sufficient I will create a blog post/article on dev.to as you suggested @alexellis

**Comment by TechGuyTN** [comment]
Ok I'm not sure why I didn't think about using gitbash before but here goes. Able to create a Multi-master HA Kubernetes using K3Sup on Windows10/Server 2019. @alexellis @vattybear  

https://github.com/TechGuyTN/K3Sup-Windows10

**Comment by alexellis** [comment]
Hi both, please feel free to go nuts - the more tutorials the merrier. There are no k3sup stickers, but I'll send you a little selection if you publish a decent blog post or lab. :-) Hope that sounds fair.
