### ISSUE TITLE
Helm not installed by default

### ISSUE THREAD

**Issue by avarf** [alexellis/k3sup#181]
Hi, I used k3sup for installing k3s on a remote machine. The installation moved smoothly and I am able to launch deployments, services, etc via yaml files but Helm was not installed by default.

I had to create all the required RBAC stuff and then run `helm init` to make helm available. This is not a hard thing to do but based on the official documentation k3s comes with a helm controller, have you disable this? I am asking because I need to install k3s on many machines and I want to know if I am doing something wrong or installing Helm separately is part of standard procedure.

My installation procedure:
Both machines are two Ubuntu 18.4 running on bare metal.
1. Installing the command-line tool on machine A:
```bash
curl -sLSf https://get.k3sup.dev | sh
sudo install ./k3sup /usr/local/bin/
```

2. Installing k3s on machine B (k3s master-node):
```bash
export MASTER_NODE_IP=10.203.101.4
k3sup install --ip $MASTER_NODE_IP --user my-user --local-path=./kubeconfig
```

3. Copying config file to make kubectl work (on machine B):
```bash
# on the MASTER_NODE
sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
sudo chown 777:777 ~/.kube/config
kubectl get nodes
```

**Comment by alexellis** [comment]
Hi I'm going to close this issue because it's not clear what the issue is.

There's no need to chown / chmod any KUBECONFIG files, they are all brought back to the host where `k3sup` is run.

To get Helm 2 or 3, you simply need to install an app that uses either

```
k3sup app install openfaas --helm3=false
k3sup app install openfaas --helm3=true
````

The binary is downloaded to $HOME/.k3sup/

For technical support please could you join Slack? Or use the issue template instead of deleting it?
