### ISSUE TITLE
Why defining KUBECONFIG=`pwd`/kubeconfig?

### ISSUE THREAD

**Issue by cmonty14** [alexellis/k3sup#225]
Hi,

I have successfully deployed k3s on Debian 10.

In the doku "Setup a Kubernetes server with k3sup" you write:
```
Now try the access:
export KUBECONFIG=`pwd`/kubeconfig
kubectl get node
```
So I logged on the node where I deployed k3s and executed this:
```
locadmin@vm185-debian10:~
$ export KUBECONFIG=`pwd`/kubeconfig
locadmin@vm185-debian10:~
$ kubectl get node
W0306 18:10:50.989794    7779 loader.go:223] Config not found: /home/locadmin/kubeconfig
The connection to the server localhost:8080 was refused - did you specify the right host or port?
locadmin@vm185-debian10:~
$ sudo kubectl get node
[sudo] password for locadmin:
NAME             STATUS   ROLES    AGE   VERSION
vm185-debian10   Ready    master   43m   v1.17.2+k3s1

```
Question:
Why should I define KUBECONFIG?

I mean there's no such directory _/home/locadmin/kubeconfig_. 

And `kubectl` is only working with _sudo_, but I guess this is expected.

THX

**Comment by Amalkh5** [comment]
@cmonty14 running  the command ``` export KUBECONFIG=`pwd`/kubeconfig ``` should be in your machine to access remote Kubernetes cluster.

**Comment by alexellis** [comment]
Hi @Amalkh5 I'm also a little confused by what this issue is about.

After running `k3sup install`, the kubeconfig file is generally outputted to `pwd`, therefore you should set the full path to the kubeconfig file before running `kubectl`.

That's the answer to "why", but is there another question you wanted to ask @cmonty14?
