### ISSUE TITLE
Join arguments are confusing

### ISSUE THREAD

**Issue by dhoard** [alexellis/k3sup#27]
k3sup join arguments are confusing. Both IPs are for servers.

Example

```
export SERVER_IP=159.65.25.233
export IP=159.65.22.30

k3sup join --ip $IP --server-ip $SERVER_IP --user root
```

Both `IP` and `SERVER_IP` are both remote servers.

A better description would be something like ...

```
k3sup join --agent-node-ip $IP --master-node-ip $SERVER_IP --user root
```

**Comment by alexellis** [comment]
Thanks for your suggestion @dhoard, I'll bear it in mind.

I've deliberated used this terminology because:

1) k3s doesn't use a `master`, it uses a `server`.
2) Your variant is going to be a pain in the neck to type in, and I deliberately want the command lines to be as short as possible, whilst still making sense.

I'm just curious, other than your personal opinion (which is useful feedback), In what way were you confused when following the guide? Did you somehow do a bad install?

**Comment by dhoard** [comment]
I was running through your blog post at (https://blog.alexellis.io/create-a-3-node-k3s-cluster-with-k3sup-digitalocean/) and it wasn't clear.

While I can understand your point of view on short commands. I feel that most users would not care, considering that this will be executed very rarely.

Adding more verbose commands that could be used along with the existing ones.

Thanks for the tool!
