### ISSUE TITLE
[Feature request] Validate that the k3s-agent started with systemd

### ISSUE THREAD

**Issue by dhoard** [alexellis/k3sup#28]
## Synopsis

The `k3sup join` command doesn't validate that the `k3s-agent` is running during the `join` process.

## Context

The `k3s-agent.service` file has a `Type=exec` which doesn't appear to be working correctly on Ubuntu 18.04.3 LTS (Rancher issue - not k3sup issue)

From the k3sup log output I see ...

```
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
```

... but the `k3s-agent` actually failed to start.

## Environment

Ubuntu 18.04.3 LTS

## Execution Scenario

Execute a join

```
export SERVER_IP=159.65.25.233
export IP=159.65.22.30

k3sup join --ip $IP --server-ip $SERVER_IP --user root
```

## Expected Behavior

```
> kubectl get node

NAME    STATUS   ROLES    AGE     VERSION
k3s-1   Ready    master   6m57s   v1.14.6-k3s.1
k3s-2   Ready    worker   55s     v1.14.6-k3s.1
```

## Actual Behavior

```
> kubectl get node

NAME    STATUS   ROLES    AGE     VERSION
k3s-1   Ready    master   6m57s   v1.14.6-k3s.1
```

**Comment by alexellis** [comment]
Thanks for the issue.

I'm pretty sure that everywhere I tested k3sup, I used Ubuntu 18.04.3 LTS. I'm surprised it isn't working... What cloud did you use?

As for checking if the agent started. Do you know any bash command that could do that?

**Comment by dhoard** [comment]
I’m an using freshly installed VMs on my local KVM machines.

For machines with systems...

```
systemctl status application.service
```

**Comment by dhoard** [comment]
You could add a function `validateAgent` in `join.go` So they you could validation code. 

I’m sure there are other things worth validating.

**Comment by alexellis** [comment]
That tends to be blocking? Does it need a human to read it, or can it be run over SSH with an exit code being parsed?

Feel free to PoC something.

**Comment by dhoard** [comment]
If you ware wanting something more pure Bash ...

```
 ps -ef | grep "k3s agent" | grep -v grep | wc -l | grep 1 > /dev/null
```

... has an exit code of `0` on a match, and `1` on no match.

**Comment by alexellis** [comment]
It seems a bit brittle. Is there an FD created maybe when systemd starts up a process?

Maybe you could ask upstream for a shell script to by provided by k3s, just like they provide an uninstaller.sh

**Comment by sourcedelica** [comment]
I got the same thing on Amazon Linux 2 following https://rancher.com/blog/2019/k3s-kubeconfig-in-seconds/

**Comment by alexellis** [comment]
There should be no error @sourcedelica if you're following the tutorial. Please can you raise a separate issue about the tutorial, then I'll ping the author to see if he can give you some technical support.

Alex

**Comment by alexellis** [comment]
@dhoard does the ssh / exec return a non-zero exit code in your example, or can it only be determined through manual checking?

**Comment by dhoard** [comment]
@alexellis not sure... but since the systemd start is asynchronous, I suspect you can’t use exit code.

**Comment by saiyam1814** [comment]
@sourcedelica I just tried again for setting up k3s using k3sup on Amazon Linux 2  using the blog and it works without giving any error. I did not do any additional step apart from what is mentioned in the blog. Please make sure you have set up the ports, running as root etc. It is very straightforward so not sure why its giving error for you. Feel free to create another issue for the same as mentioned by @alexellis  earlier so that we can have a detailed discussion on it.

![image](https://user-images.githubusercontent.com/8190114/64529582-e4a9da00-d328-11e9-823d-802f3bb5ae7e.png)

**Comment by sourcedelica** [comment]
Sounds good, thanks

**Comment by rbucker** [comment]
Not all Linux distros are the same. I urge that this ticket be reopened or forked... I ran the install and join commands against VMware's PhotonOS v3 and had the same two errors.

- systemd type:exec error
- CA File missing and certs

If this is something that the user is supposed to do then a link to the docs would be helpful because not even the k3s docs mention these issues.
