### ISSUE TITLE
Worker node not joining the cluster

### ISSUE THREAD

**Issue by dannyjknights** [alexellis/k3sup#296]
## k3sup join successful but not showing as part of the cluster
I ran the `k3sup join --ip 192.168.0.49 --server-ip 192.168.0.45` command and it completed correctly. SSH onto the worker node now gives me `kubectl` command options. 

When going on to the master node and running `sudo kubectl get node`, I only see the master and not the worker.

Has anyone come across this issue before? Apologies as I'm a bit of a newbie here and trying to build a lab for self-learning.

## Your Environment

* Raspberry Pi 3 Model B Quad Core CPU 1.2 GHz 1 GB RAM

* 2020-02-13-raspbian-buster-lite.img

* k3sup v1.19

**Comment by alexellis** [comment]
Hi you're not meant to run kubectl on the server at all. That's why you get a local file.

You'll have to debug k3s yourself - look at the logs on your agent and server process. The k3s docs should help you there.

Closing this as technical support, rather than a bug. Happy to reopen if you can prove we have a bug in k3sup. 

Also make sure you follow a tutorial so you are enabling cgroups in your cmdline file. 

https://alexellisuk.medium.com/walk-through-install-kubernetes-to-your-raspberry-pi-in-15-minutes-84a8492dc95a
Alex

**Comment by dannyjknights** [comment]
Thank you Alex and apologies, it's not a bug as you rightly say, I was just looking for some help and didn't know where to ask it. I will read your tutorial and look at the logs. So am I not supposed to run `sudo kubectl get node` from the master node?

Many thanks for getting back to me

**Comment by alexellis** [comment]
This is the workflow.

From your laptop run k3sup - either merge the Kubeconfig or save it to a local file.

Next, point your local kubectl at that config file.

Next, do whatever you need to, just like with a managed cloud.

You can also run arkade in the same way and use k3sup to add additional nodes in. 

Rancher slack is a good place to get k3s support, and check their docs. You need to look at the k3s and k3s-agent processes.

If in doubt, follow my tutorial to the letter without customising it.
