### ISSUE TITLE
unknown flag: --no-extras for join

### ISSUE THREAD

**Issue by Cloud-Mak** [alexellis/k3sup#408]
Hello,

Supppose you want to disable servicelb and traefik while joinig the nodes. The github front page documentation says --no-extras will do both. But this doesn not working with joing commnd. Below is error

> Error: unknown flag: --no-extras

Had to specify 

`--k3s-extra-args " --disable traefik --disable servicelb`

to get it working.

**Comment by rgee0** [comment]
`—no-extras` is a flag on the `install` command, rather than `join`. 

To enable an appropriate update to the docs, can you provide details of where in the docs you saw it mentioned in the context of `join` please?

**Comment by alexellis** [comment]
I'd echo what @rgee0 said.

The agent/workers do not / should not accept this flag as they don't configure the cluster, servers do.

If you would like support, you'll need to fill out the issue template and provide repo instructions instead of deleting it and writing what you think you'd like to share. Unfortunately, it has just made it really difficult to be able to help you.

https://raw.githubusercontent.com/alexellis/k3sup/master/.github/ISSUE_TEMPLATE.md

I'll get this closed, but re-open it if you edit and fill in all the template.
