### ISSUE TITLE
Certificate Error: get.k3sup.dev invalid domain

### ISSUE THREAD

**Issue by scog** [alexellis/k3sup#435]
## Why do you need this?

* Unable to install k3s using `k3sup` instructions.

## Expected Behaviour

* Did not expect to get certificate error for invalid hostname

## Current Behaviour

```
:~$ curl -sLS https://get.k3sup.dev
curl: (60) SSL: no alternative certificate subject name matches target host name 'get.k3sup.dev'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
````

![Screenshot 2024-04-25 at 10 58 51 AM](https://github.com/alexellis/k3sup/assets/1134176/d050eca1-2107-4c3f-a0d5-222610f6fa8d)

## Possible Solution

* Passing `--insecure`

## Steps to Reproduce

1. Run `curl -sLS https://get.k3sup.dev`

## Your Environment

* Ubuntu 22.04 LTS

## Do you want to work on this?

- [ ] Yes
- [X] No

**Comment by alexellis** [comment]
Hi Drew thanks for your interest in k3sup.

Unfortunately this issue is the result of Google Domains being acquired by Squarespace, and Squarespace having technical difficulties. See: 

I'd suggest you use arkade to download k3sup until Squarespace sort out their TLS certs for migrated customers.

```bash
curl -SLs https://get.arkade.dev | sh
arkade get k3sup
```

As [I mentioned here](https://github.com/alexellis/arkade/issues/1056), if you or anyone else landing here relies on my work, then [you can sponsor me via GitHub](https://github.com/sponsors/alexellis).

Alex

**Comment by scog** [comment]
Sounds good. Just wanted to report the issue. Closing this ticket.
